### ISSUE TITLE
Horrible error with fourth_dimension.py

### ISSUE THREAD

**Issue by Templarfreak** [leios/simuleios#27]
I'm not sure what's causing it, I may have done something wrong, but on v2.78c the script is completely non-functional. The edges get placed somewhere far off and no rotation seems to occur at all. The only thing that does seem to happen is the light source slowly moves.

**Comment by leios** [comment]
Hey Templarfreak, there is more than one visualization in this file. By default, I set the visualization to be of the second-to-last visualization in the video -- the one of a light source moving in and out and casting a shadow on the plane underneath. This is the expected behavior. 

If you want to see the 4d rotation, simply comment out line 668 and comment in line 669. In this case, the visualization will have a constantly changing light source. If you want a constant light source, change `val` on lines 559 and 560 to be a constant.

Again, I apologize for the code being so messy. My hope was that the video, itself, would provide enough information for anyone who wanted to to code ti up themselves without relying on my scripts.

Let me know if you have any other problems!

**Comment by Templarfreak** [comment]
So the default visualization is to render a cube? That's weird. I don't understand why you'd make that one the default considering what people are probably downloading the script for and they'd basically have to be able to read the entire script in order to know that. Perhaps it should be in a comment at the top of the script with the rest of that stuff.

Anyway, thanks for the help and sorry to be a bother. Giving it another go at rendering right now, will probably update this comment with the results (If it worked or not).

**Comment by Templarfreak** [comment]
One last thing: What exactly are the limitations of visualize_fourth_dimension? I put in 102, 1025, 3321, but that's clearly beyond it's limits. Maybe an explanation of what these 3 values actually mean would help me understand. (In visualize_fourth_dimension(1, 1000, 1000)) All they are labelled as is res1, res2, and rot_res. I can only guess that res is short for resolution but I'm not sure what that means in context here.
